doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: false
        mappings:
            App\Core\Component\Company\Domain\Company:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/doctrine/Company'
                prefix: 'App\Core\Component\Company\Domain'
                alias: Company
            App\Core\Component\Company\Domain\Worker\Worker:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/doctrine/Company/Worker'
                prefix: 'App\Core\Component\Company\Domain\Worker'
                alias: Worker
            App\Core\Component\Company\Domain\Address\Address:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/doctrine/Company/Address'
                prefix: 'App\Core\Component\Company\Domain\Address'
                alias: Address
when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
