App\Core\Component\Company\Domain\Worker\Worker:
    type: entity
    table: worker
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        firstName:
            type: string
        lastName:
            type: string
        email:
            type: string
        phoneNumber:
            type: string
            nullable: true
    manyToOne:
        company:
            targetEntity: App\Core\Component\Company\Domain\Company
            inversedBy: workers
            joinColumn:
                nullable: false
