api_company_show:
    path:       /api/company/{id}
    controller: App\Presentation\Component\Company\Controller\API\CompanyShowController::show
    methods:    GET|HEAD
api_company_create:
    path:       /api/company
    controller: App\Presentation\Component\Company\Controller\API\CompanyCreateController::create
    methods:    POST
api_company_update:
    path:       /api/company/{id}
    controller: App\Presentation\Component\Company\Controller\API\CompanyUpdateController::update
    methods:    POST
api_company_delete:
    path:       /api/company/{id}
    controller: App\Presentation\Component\Company\Controller\API\CompanyDeleteController::delete
    methods:    DELETE


api_worker_show:
    path:       /api/worker/{id}
    controller: App\Presentation\Component\Company\Controller\API\Worker\WorkerShowController::show
    methods:    GET|HEAD
api_worker_create:
    path:       /api/worker
    controller: App\Presentation\Component\Company\Controller\API\Worker\WorkerCreateController::create
    methods:    POST
api_worker_update:
    path:       /api/worker/{id}
    controller: App\Presentation\Component\Company\Controller\API\Worker\WorkerUpdateController::update
    methods:    POST
api_worker_delete:
    path:       /api/worker/{id}
    controller: App\Presentation\Component\Company\Controller\API\Worker\WorkerDeleteController::delete
    methods:    DELETE
